[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.60
blur = true
decorations = "transparent"
startup_mode = "SimpleFullscreen"
dynamic_padding = true
